export const announcements = [
  {
    text: "⚡ Flash Sale! 50% off all tickets for the next",
    hasSale: true,
    endTime: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 hours from now
  },
  {
    text: "🎁 Buy one ticket, get one free this weekend only! Ends in",
    hasSale: true,
    endTime: new Date(Date.now() + 48 * 60 * 60 * 1000), // 48 hours from now
  },
  {
    text: "⏰ Limited time offer: Marvel collection drawing closes soon!",
    hasSale: false,
  },
  {
    text: "🏷️ New members: Use code WELCOME10 for 10% off your first ticket",
    hasSale: false,
  },
  {
    text: "🔥 Hot Deal! Hogwarts Castle tickets just restocked!",
    hasSale: false,
  },
];

// Badge categories
export const BADGE_CATEGORIES = {
  WELCOME: {
    text: "WELCOME TO BRICK DRAFT",
    className: "bg-accent text-black",
  },
  SALE: {
    text: "SALE",
    className: "bg-red-500 text-white",
  },
  NEW: {
    text: "NEW ARRIVAL",
    className: "bg-green-500 text-black",
  },
  SPECIAL: {
    text: "SPECIAL OFFER",
    className: "bg-purple-500 text-white",
  },
  COLLECTION: {
    text: "COLLECTION",
    className: "bg-blue-500 text-white",
  },
};

export const banners = [
  {
    image:
      "https://static1.dualshockersimages.com/wordpress/wp-content/uploads/2017/09/lego_world.jpg?q=50&fit=crop&w=1140&h=&dpr=1.5",
    badge: BADGE_CATEGORIES.WELCOME,
    title: "Build Your LEGO Dreams One Brick at a Time",
    description:
      "Save up to 70% compared to retail prices while enjoying the thrill of building your collection one brick at a time. It's like a treasure hunt for LEGO enthusiasts!",
    primaryLink: {
      text: "How It Works",
      href: "/about",
    },
    showVideoButton: true,
    videoUrl:
      "https://drive.google.com/file/d/1XWC_0rZ9wcN7324J2t8FIz9psIrndBhs/preview",
  },

  {
    image:
      "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExYmRsMHpuaTdza2Fkd2c4NXpxYnpiN2Iwd25rMG9naWVjeWVkNWdwbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/1xljZ6jByg4EnptnTz/giphy.gif",
    badge: BADGE_CATEGORIES.NEW,
    title: "Join the Galactic Empire\nBuild Your Star Wars Legacy!",
    description:
      "Collect iconic Star Wars LEGO sets from a galaxy far, far away. From the Millennium Falcon to the Death Star, your collection awaits!",
    primaryLink: {
      text: "Explore Star Wars Sets",
      href: "/lottery/all",
    },
  },
  {
    image:
      "https://res.cloudinary.com/dhpccjumk/image/upload/v1745979338/ssmwbbvdfkpxp0h6y59o.png",
    badge: BADGE_CATEGORIES.SALE,
    title: "Final Hours to Enter Drawing!",
    description:
      "Don't miss your chance to win this incredible set. Enter now before the drawing closes.",
    timer: {
      label: "Drawing Closes In:",
      endDate: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(), // 48 hours from now
    },
    primaryLink: {
      text: "Buy Ticket Now",
      href: "/lottery/all",
    },
  },
  {
    image:
      "https://res.cloudinary.com/dhpccjumk/image/upload/v1745935011/htpgltdpfo3bqdfv4sps.webp",
    badge: BADGE_CATEGORIES.COLLECTION,
    title: "Assemble Your Marvel LEGO Collection",
    description:
      "Enter to win exclusive Marvel sets and build your own superhero universe!",
    primaryLink: {
      text: "View Marvel Sets",
      href: "/lottery/all",
    },
  },
  {
    image:
      "https://res.cloudinary.com/dhpccjumk/image/upload/v1745937598/incgz1c6x2jr6x9roffd.webp",
    badge: BADGE_CATEGORIES.SPECIAL,
    title: "BUY ONE GET ONE FREE!",
    description:
      "Buy any ticket this weekend and get a second entry absolutely FREE. Limited time offer!",
    timer: {
      label: "Offer Ends In:",
      endDate: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(), // 72 hours from now
    },
    primaryLink: {
      text: "Claim Offer Now",
      href: "/lottery/all",
    },
  },
];


export const THEMES = {
  WINTER_CABIN: "Winter Cabin",
  HARRY_POTTER: "Harry Potter",
  ICONS: "Icons",
  ARCHITECTURE: "Architecture",
  SUPER_MARIO: "Super Mario",
  TECHNIC: "Technic",
  NASA: "NASA",
  NINJAGO: "NINJAGO",
  DISNEY: "Disney",
  GHOSTBUSTERS: "Ghostbusters",
  IDEAS: "Ideas",
  CREATOR_EXPERT: "Creator Expert",
  BOTANICAL: "Botanical Collection",
  MARVEL: "Marvel"
};

export const FEATURES = {
  FEATURED: "Featured",
  BEST_SELLER: "Best Seller",
  NEW_ARRIVAL: "New Arrival",
  LIMITED_EDITION: "Limited Edition"
};

export const lotteryData = [
  {
    id: "cozy-house",
    name: "Cozy House",
    description: "A charming winter cabin with detailed interior and exterior features. Perfect for display or play.",
    price: 10.99,
    marketPrice: 99,
    drawDate: "May 18, 2025",
    drawTime: "3:00 PM EST",
    totalSlots: 50,
    slotsAvailable: 10,
    image:
      "https://m.media-amazon.com/images/S/aplus-media-library-service-media/74eb261c-f265-4c3d-910e-084f4240b9ed.__CR0,0,970,600_PT0_SX970_V1___.jpg",
    features: [FEATURES.FEATURED],
    pieces: 350,
    theme: THEMES.WINTER_CABIN,
    dateAdded: "2025-05-15",
  },
  {
    id: "hogwarts-castle",
    name: "Hogwarts Castle",
    description: "Detailed microscale model of the iconic Hogwarts School of Witchcraft and Wizardry.",
    price: 2.99,
    marketPrice: 429,
    drawDate: "May 19, 2025",
    drawTime: "2:00 PM EST",
    totalSlots: 100,
    slotsAvailable: 25,
    image: "https://buildamoc.com/cdn/shop/products/bZI9Ov4oaJ.jpg?v=1653507186&width=2048",
    features: [FEATURES.FEATURED],
    pieces: 6020,
    theme: THEMES.HARRY_POTTER,
    dateAdded: "2025-05-15",
  },
  {
    id: "titanic",
    name: "LEGO Titanic",
    description: "Authentic 1:200 scale model of the ill-fated ocean liner with incredible interior details.",
    price: 3.5,
    marketPrice: 679,
    drawDate: "May 20, 2025",
    drawTime: "4:30 PM EST",
    totalSlots: 120,
    slotsAvailable: 40,
    image: "https://m.media-amazon.com/images/I/61l9pB4kA+L._AC_UF1000,1000_QL80_.jpg",
    features: [],
    pieces: 9090,
    theme: THEMES.ICONS,
    dateAdded: "2025-05-15",
  },
  {
    id: "colosseum",
    name: "Roman Colosseum",
    description: "Recreate the mighty Colosseum with this detailed architectural model.",
    price: 2.5,
    marketPrice: 549,
    drawDate: "May 21, 2025",
    drawTime: "1:00 PM EST",
    totalSlots: 80,
    slotsAvailable: 15,
    image: "https://m.media-amazon.com/images/I/71fIlRTYRZL._AC_UF894,1000_QL80_.jpg",
    features: [],
    pieces: 9036,
    theme: THEMES.ARCHITECTURE,
    dateAdded: "2025-05-15",
  },
  {
    id: "eiffel-tower",
    name: "Eiffel Tower",
    description: "Build the iconic Parisian landmark in stunning detail with this towering set.",
    price: 3.99,
    marketPrice: 629,
    drawDate: "May 22, 2025",
    drawTime: "5:00 PM EST",
    totalSlots: 90,
    slotsAvailable: 30,
    image: "https://m.media-amazon.com/images/I/717Ph4gd2tL._AC_SL1500_.jpg",
    features: [],
    pieces: 10001,
    theme: THEMES.ICONS,
    dateAdded: "2025-05-15",
  },
  {
    id: "super-mario-bowsers-castle",
    name: "Super Mario Bowser's Castle",
    description: "Enter the world of Super Mario with this detailed recreation of Bowser's Castle.",
    price: 5.99,
    marketPrice: 399,
    drawDate: "May 23, 2025",
    drawTime: "2:30 PM EST",
    totalSlots: 75,
    slotsAvailable: 20,
    image: "https://www.toysrus.ca/dw/image/v2/BDFX_PRD/on/demandware.static/-/Sites-toys-master-catalog/default/dwc36baea1/images/4466280B_7.jpg?sw=767&sh=767&sm=fit",
    features: [FEATURES.FEATURED],
    pieces: 2807,
    theme: THEMES.SUPER_MARIO,
    dateAdded: "2025-05-15",
  },
  {
    id: "technic-bugatti-chiron",
    name: "Technic Bugatti Chiron",
    description: "Advanced building set featuring the iconic supercar with working mechanics.",
    price: 2.99,
    marketPrice: 349,
    drawDate: "May 24, 2025",
    drawTime: "3:30 PM EST",
    totalSlots: 60,
    slotsAvailable: 18,
    image: "https://preview.redd.it/q59d3x5n0gf41.jpg?width=1080&crop=smart&auto=webp&s=d6f74fbe7a55246b29c104fcb6f2086232298818",
    features: [],
    pieces: 3599,
    theme: THEMES.TECHNIC,
    dateAdded: "2025-05-15",
  },
  {
    id: "nasa-space-shuttle",
    name: "NASA Space Shuttle Discovery",
    description: "Authentic replica of the NASA Space Shuttle Discovery with Hubble Space Telescope.",
    price: 6.99,
    marketPrice: 199,
    drawDate: "May 25, 2025",
    drawTime: "12:00 PM EST",
    totalSlots: 40,
    slotsAvailable: 12,
    image: "https://m.media-amazon.com/images/I/81sRq4NIg-L._AC_SL1500_.jpg",
    features: [],
    pieces: 2354,
    theme: THEMES.NASA,
    dateAdded: "2025-05-15",
  },
  {
    id: "ninjago-city",
    name: "NINJAGO City Gardens",
    description: "Celebrate 10 years of NINJAGO with this detailed modular city set.",
    price: 3.99,
    marketPrice: 299,
    drawDate: "May 26, 2025",
    drawTime: "4:00 PM EST",
    totalSlots: 70,
    slotsAvailable: 35,
    image: "https://i5.walmartimages.com/asr/17e6ea0b-3cb7-461e-bb1f-1bcf3f1e93c4.170f600a5d45d2bb0a7777688e73b8a6.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF",
    features: [],
    pieces: 5685,
    theme: THEMES.NINJAGO,
    dateAdded: "2025-05-15",
  },
  {
    id: "disney-castle",
    name: "Disney Castle",
    description: "Magical Disney Castle inspired by Walt Disney World's Cinderella Castle.",
    price: 4.99,
    marketPrice: 399,
    drawDate: "May 27, 2025",
    drawTime: "3:00 PM EST",
    totalSlots: 85,
    slotsAvailable: 25,
    image: "https://i.redd.it/i-built-disneylands-sleeping-beauty-castle-in-lego-v0-383rlgg5ttdc1.jpg?width=2964&format=pjpg&auto=webp&s=67669e51675b6a653228eed1bda6a0cd23b99236",
    features: [],
    pieces: 4080,
    theme: THEMES.DISNEY,
    dateAdded: "2025-05-15",
  },
  {
    id: "ghostbusters-ecto-1",
    name: "Ghostbusters ECTO-1",
    description: "Detailed recreation of the iconic ghost-hunting vehicle from the Ghostbusters movies.",
    price: 2.99,
    marketPrice: 199,
    drawDate: "May 28, 2025",
    drawTime: "2:00 PM EST",
    totalSlots: 45,
    slotsAvailable: 15,
    image: "https://www.elyswimbledon.co.uk/cdn/shop/files/lego-lego-ghostbuster-ecto-1-28519702462549_1600x.jpg?v=1697464799",
    features: [],
    pieces: 2352,
    theme: THEMES.GHOSTBUSTERS,
    dateAdded: "2025-05-15",
  },
  {
    id: "ideas-tree-house",
    name: "Ideas Treehouse",
    description: "Sustainable treehouse set with interchangeable summer and autumn leaves.",
    price: 2.99,
    marketPrice: 199,
    drawDate: "May 29, 2025",
    drawTime: "1:30 PM EST",
    totalSlots: 50,
    slotsAvailable: 20,
    image: "https://i.ebayimg.com/images/g/KEEAAOSwEKVfkGVM/s-l1200.jpg",
    features: [],
    pieces: 3036,
    theme: THEMES.IDEAS,
    dateAdded: "2025-05-15",
  },
  {
    id: "creator-expert-bookshop",
    name: "Creator Expert Bookshop",
    description: "Modular building featuring a quaint bookshop and adjoining townhouse.",
    price: 3.99,
    marketPrice: 179,
    drawDate: "May 30, 2025",
    drawTime: "3:30 PM EST",
    totalSlots: 55,
    slotsAvailable: 22,
    image: "https://www.brickfanatics.com/wp-content/uploads/LEGO-Creator-Expert-10270-Bookshop-featured-3.jpg",
    features: [],
    pieces: 2504,
    theme: THEMES.CREATOR_EXPERT,
    dateAdded: "2025-05-15",
  },
  {
    id: "botanical-collection-orchid",
    name: "Botanical Collection Orchid",
    description: "Elegant orchid plant that never needs watering, perfect for home decor.",
    price: 4.99,
    marketPrice: 49,
    drawDate: "May 31, 2025",
    drawTime: "12:30 PM EST",
    totalSlots: 30,
    slotsAvailable: 8,
    image: "https://jaysbrickblog.com/wp-content/uploads/2022/04/LEGO-10311-Orchid-Wood-Background.jpg",
    features: [],
    pieces: 608,
    theme: THEMES.BOTANICAL,
    dateAdded: "2025-05-15",
  },
  {
    id: "marvel-sanctum-sanctorum",
    name: "Marvel Sanctum Sanctorum",
    description: "Doctor Strange's magical headquarters with scenes from the Marvel movies.",
    price: 3.99,
    marketPrice: 249,
    drawDate: "June 1, 2025",
    drawTime: "2:30 PM EST",
    totalSlots: 65,
    slotsAvailable: 30,
    image: "https://res.cloudinary.com/dhpccjumk/image/upload/v1745980327/udyolsazsphmdiggrx1c.jpg",
    features: [],
    pieces: 2708,
    theme: THEMES.MARVEL,
    dateAdded: "2025-05-15",
  },
  {
    id: "marvel-iron-man-lab",
    name: "Marvel Iron Man Lab",
    description: "Tony Stark's high-tech lab filled with iconic suits and gear from Iron Man's legacy.",
    price: 4.49,
    marketPrice: 299,
    drawDate: "June 2, 2025",
    drawTime: "4:00 PM EST",
    totalSlots: 70,
    slotsAvailable: 28,
    image: "https://ideascdn.lego.com/media/generate/entity/lego_ci/project/47f0bfe1-2f95-403b-bcb3-d169da5d866a/1/resize:1600:900/legacy",
    features: [FEATURES.FEATURED],
    pieces: 3210,
    theme: THEMES.MARVEL,
    dateAdded: "2025-05-15",
  },
  {
    id: "marvel-wakanda-throne-room",
    name: "Marvel Wakanda Throne Room",
    description: "Recreate the royal heart of Wakanda with T'Challa, Shuri, and Dora Milaje.",
    price: 3.75,
    marketPrice: 215,
    drawDate: "June 3, 2025",
    drawTime: "1:00 PM EST",
    totalSlots: 60,
    slotsAvailable: 25,
    image: "https://bricksfanz.com/wp-content/uploads/2022/09/76213-King-Namors-Throne-Room.jpg",
    features: [],
    pieces: 1987,
    theme: THEMES.MARVEL,
    dateAdded: "2025-05-15",
  },
  {
    id: "marvel-avengers-tower",
    name: "Marvel Avengers Tower",
    description: "The iconic Avengers HQ filled with action scenes and legendary heroes.",
    price: 5.25,
    marketPrice: 399,
    drawDate: "June 5, 2025",
    drawTime: "2:00 PM EST",
    totalSlots: 80,
    slotsAvailable: 35,
    image: "https://m.media-amazon.com/images/I/81ncz3UF2rL._AC_SL1500_.jpg",
    features: [FEATURES.FEATURED],
    pieces: 3985,
    theme: THEMES.MARVEL,
    dateAdded: "2025-05-15",
  },
  {
    id: "marvel-guardians-ship",
    name: "Marvel Guardians' Ship",
    description: "Join Star-Lord and the Guardians of the Galaxy on their interstellar adventures.",
    price: 3.49,
    marketPrice: 231,
    drawDate: "June 6, 2025",
    drawTime: "5:30 PM EST",
    totalSlots: 55,
    slotsAvailable: 20,
    image: "https://i.ebayimg.com/images/g/qBcAAOSw52li6~g0/s-l1200.jpg",
    features: [],
    pieces: 2520,
    theme: THEMES.MARVEL,
    dateAdded: "2025-05-15",
  },
];